config/routes.rb
ArirangHouseROR::Application.routes.draw do
  resources :reservations

  devise_for :admins

  get "about" => 'pages#about'
  root :to => 'pages#home'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  attr_accessible :content, :name, :published, :title, :user_email
  before_create :set_publish_default_time

  def set_publish_default_time
  	self.published = Time.now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reservations }
    end
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
    @reservation = Reservation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reservation }
    end
  end

  # GET /reservations/new
  # GET /reservations/new.json
  def new
    @reservation = Reservation.new(published: Time.now)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reservation }
    end
  end

  # GET /reservations/1/edit
  def edit
    @reservation = Reservation.find(params[:id])
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(params[:reservation])

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render json: @reservation, status: :created, location: @reservation }
      else
        format.html { render action: "new" }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reservations/1
  # PUT /reservations/1.json
  def update
    @reservation = Reservation.find(params[:id])

    respond_to do |format|
      if @reservation.update_attributes(params[:reservation])
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy

    respond_to do |format|
      format.html { redirect_to reservations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>
		©2013, Kuwait Arirang-House, CEO: 김재철, 관리자: 김현태	 <br/>
		<b>email:</b> kookhee54@hanmail.net, barty82@naver.com / <b>phone (Local):</b> (+965), 9715-4872 / <b>phone (internet Phone):</b> (+82) 070-7098-5671  <br/>
		
	</small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to "Arirang Guest House", root_path, class: "brand" %>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li><%= link_to "Home", root_path %> </li>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Facilities", "#" %></li>
          <li><%= link_to "Reservation", "#" %></li>
          <li><%= link_to "Contact", "#" %></li>
        </ul>
        <ul class="nav pull-right">
          <li><%= link_to "Map", "#" %> </li>

          <% if admin_signed_in? %>
            <li><%= link_to "Logout", destroy_admin_session_path, method: :delete %> </li>
          <% else %>
            <li><%= link_to "Admin", new_admin_session_path %> </li>
          <% end %>
        </ul>
      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ArirangHouseROR</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div class="container">
	<% flash.each do |name, msg| %>
		<%= content_tag(:div, msg, class:"alert alert-#{name}") %>
	<% end %>
	<%= yield %>
	<%= render 'layouts/footer' %>	
</div>


</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>
	<%= link_to "Arirang Guest House", "http://www.arirangguesthouse.co.kr" %> is a promotional web site for my parents. This is the first version of web-application contains DB.
</p>

app/views/pages/home.html.erb
<% if admin_signed_in? %>
	<h1>Hi Mam!</h1>
<% else %>
	<div class="hero-unit">
		<h1>환영합니다</h1>
		<br/>
		<p>
			당신의 진정한 사업 파트너가 되어 드리겠습니다. <br/>
			쿠웨이트 아리랑 하우스<br/><br/>
			<button class="btn btn-large btn-primary" type="button">예약하기</button>
		</p>
	</div>

	<div class="row-fluid">
		<div class="span4">
			<h2>인사말</h2>
			<p>
				"안녕하세요. 저희 게스트 하우스는 쿠웨이트 한인 게스트 하우스의 최초이자 최고의 숙박 업체로써 여러분들의 최고의 Business 파트너가 되어 드리겠습니다. 저희 홈페이지에서는 단순한 숙박정보를 제공하는 것 이상으로 쿠웨이트 한인 커뮤니티의 인터넷 Link도 제공하고 있습니다."
			</p>
			<p>
				<a class="btn" href="#">View details</a>
			</p>
		</div>
		<div class="span4">
			<h2>서비스 안내</h2>
			<p>
				"로컬 호텔 숙박비가 부담이 되신다구요? 혹은 한국음식 없이 지낼 수 없으시다구요? 저희 아리랑 하우스에서는 집에서 만든 심식(한식)제공을 하오며, 세탁, 고속 인터넷 사용 가능등 여러분들이 지내시는데 불편함 없는 환경을 제공해 드리고 있습니다."
			</p>
			<p>
				<a class="btn" href="#">자세히 보기</a>
			</p>
		</div>
		<div class="span4">
			<h2>편의시설</h2>
			<p>
				"저희는 지하를 포함한 4층짜리 단독 주택을 이용하여 2인 객실 7개, 1인 독실 2개를 포함한 총 9개의 방으로 최대 16명까지 수용할 수 있습니다. 그리고 탁구, 당구, 무선 인터넷, 50여편의 VOD 영화등을 부대시설을 통해 즐거운 여가를 즐길 수 있습니다."
			</p>
			<p>
				<a class="btn" href="#">자세히 보기</a>
			</p>
		</div>
	</div>
	<hr>
<% end %>

app/views/reservations/_form.html.erb
<%= simple_form_for(@reservation, html:{class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

  <%= f.input :name, label: "성함" %>
  <%= f.input :user_email, label: "이메일" %>
  <%= f.input :title, label: "제목" %>
  <%= f.input :content, label: "자세한 내용", input_html:{rows: 9}%>

  <%= @reservation.published %>
  


  <div class="form-actions">
    <%= f.button :submit,  "예약하기" , class: "btn btn-primary" %>
  </div>
<% end %>

app/views/reservations/_reservation.html.erb
<tr>
  <td><%= reservation.published %></td>
  <td><%= reservation.name %></td>
  <td><%= reservation.title %></td>
  <td><%= link_to '자세히 보기', reservation %></td>
  <td><%= link_to '수정하기', edit_reservation_path(reservation) %></td>
  <td><%= link_to '삭제하기', reservation, method: :delete, data: { confirm: '정말 삭제 하시겠습니까?' } %></td>
</tr>

app/views/reservations/edit.html.erb
<h1>Editing reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<h1>예약요청 리스트</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>작성일</th>
      <th>성함</th>
      <th>제목</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= render @reservations %>
  </tbody>

</table>

<br />

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/new.html.erb
<h1>예약하기</h1>

<%= render 'form' %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<div class="row">
	<div class="span6 offset3">
		<div class="well">
			<p>
			  <%= @reservation.name %>
			</p>
			<p>
			  <%= @reservation.title %>
			</p>
			<p>
			  <%= @reservation.content %>
			</p>
			<p>
			  <%= @reservation.published %>
			</p>
			<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
			<%= link_to 'Back', reservations_path %>
		</div>
	</div>
</div>